import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import React, {useRef} from "react";
import styles from '@/styles/Home.module.css'
import {Header} from '../components/Header'



export default function App({ Component, pageProps }: AppProps) {
  
    return (
      <>
        <Head>
          <title>EMI Website</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <Component {...pageProps} />
        <div className={styles.editor}>
          Work | 2022 All Rights Reserved
        </div>
      </>
  )
}
